import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" id="root">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <nav className="bg-cyan-700 p-2 text-lg text-white flex justify-around">
          <a className="hover:underline" href="/">
            Home
          </a>
          <a className="hover:underline" href="/theme">
            Theme
          </a>
        </nav>
        {children}
      </body>
    </html>
  );
}
